### ISSUE TITLE
Add maven project and basic pages (readme, history, howto)

### ISSUE THREAD

**Issue by julianhyde** [Stream-SQL-TCK/Stream-SQL-TCK#1]
Add maven project and basic pages (readme, history, howto).

**Comment by ebegoli** [comment]
I think having a description of the project in readme, or better a wiki that the describes the project, the intent, design, and the structure, would be good.

**Comment by julianhyde** [comment]
Sure, log an issue for that.

My preference is not to use wiki. If people want to make contributions, they can create pull requests. In my experience wikis end up non-linear, inconsistent and incomplete.

**Comment by julianhyde** [comment]
Fixed in f4bdd20b760c704b3217b05875ab0d0404e9c87e.

@ebegoli There is some overlap between that commit and your two open PRs. Can you review/revise those PRs?
